Apply quick optimizations to the collision model
Qfusion/qfusion pull request #388
Opened 2017-05-29 16:01 UTC by dnk777

Bounds reconstruction code has been simplified since the first attempt.

2017-06-19 08:51 UTC, viciious commented on source/qcommon/cm_q3bsp.c
> +#define MAX_MAP_BOUNDS ( 65535 )
I don't quite like this

2017-06-19 08:51 UTC, viciious commented on source/qcommon/cm_q3bsp.c
> +	// Make sure each brush is collidable by assigning maximum feasible bounds to bogus brushes
What's the purpose of this code block? So what if any of the bounds is less than -64k or greater than 64k?

2017-06-19 08:51 UTC, viciious commented on source/qcommon/cm_q3bsp.c
> +		if( brush->mins[i] < -MAX_MAP_BOUNDS || brush->maxs[i] > MAX_MAP_BOUNDS ) {
You're confusing mins with maxs in the second check here.

2017-06-19 08:51 UTC, viciious commented on source/qcommon/cm_trace.c
> +	VectorSet( cms->box_brush->mins, -99999, -99999, -99999 );
This should either be +-MAX_MAP_BOUNDS (which I dislike anyway) or the BoundsIntersect-check should be skipped for this fake brush altogether.

2017-06-19 08:51 UTC, viciious commented on source/qcommon/cm_trace.c
> +	VectorSet( cms->oct_brush->mins, -99999, -99999, -99999 );
Same as above.

2017-06-19 08:52 UTC, viciious commented on source/qcommon/cm_q3bsp.c
> +	// spread facet mins/maxs by a unit
Are you sure about this?

2017-06-19 15:17 UTC, dnk777 commented on source/qcommon/cm_q3bsp.c
> +	// spread facet mins/maxs by a unit
Yes. Moreover it was used in the original code (but these bounds were local variables and were not saved) IIRC. The purpose of it is to prevent rejection of potentially collidable item due to floating-point errors. This way is a conservative approach. In worst case it just forces a test to be executed, but prevents illegal rejection of a collidable item due to mentioned errors.

2017-06-19 15:21 UTC, dnk777 commented on source/qcommon/cm_trace.c
> +	VectorSet( cms->box_brush->mins, -99999, -99999, -99999 );
This is a thing I dislike, the same code is used for testing with a single box/octagon and leaf brushes of a collision hierarchy. Rather the code should be separated on higher level for these cases. If a flag is added, it just adds an extra branch for solid world brushes. Yes, bounds tests adds an extra branch for these single box tests, but they are rarely done compared to tracing through a solid BSP world.

2017-06-19 15:23 UTC, dnk777 commented on source/qcommon/cm_q3bsp.c
> +		if( brush->mins[i] < -MAX_MAP_BOUNDS || brush->maxs[i] > MAX_MAP_BOUNDS ) {
I have rewritten this part of code to be more clear. There is not an error
```
// Make sure each brush is collidable by assigning maximum feasible bounds to bogus brushes
for( i = 0; i < 3; i++ ) {
	// If illegal bounds set by the ClearBounds() call have not been modified for an i-th vector component
	if( brush->mins[i] >= brush->maxs[i] ) {
		brush->mins[i] = -MAX_MAP_BOUNDS;
		brush->maxs[i] = +MAX_MAP_BOUNDS;
	}
}
```

I have also added a similar validation of bounds for facets too.

2017-06-19 16:18 UTC, viciious commented
Anyway, having MAX_MAP_BOUNDS kinda sucks I would like to have it gone.

2017-06-19 16:37 UTC, dnk777 commented
Are you concerned about this exact value might be changed in future? What about using INT_MAX for it?

2017-06-20 08:20 UTC, viciious commented
We've managed to survive without this constant for years and the relatively unimportant change in this PR doesn't justify its existence.

2017-06-20 09:35 UTC, dnk777 commented
I can't read thoughts... Please describe what should I do in order to comply with your requirements. Substitute the value to all call sites instead?

2017-06-20 11:31 UTC, viciious requested changes

2017-06-20 11:31 UTC, viciious commented on source/qcommon/cm_trace.c
> +	// Make sure CM_CollideBox() will not reject the brush by its bounds
Use cms->world_mins/maxs here

2017-06-20 11:31 UTC, viciious commented on source/qcommon/cm_trace.c
> +	// Make sure CM_CollideBox() will not reject the brush by its bounds
Use cms->world_mins/maxs here

2017-06-20 11:31 UTC, viciious commented on source/qcommon/cm_q3bsp.c
> +		// If illegal bounds set by the ClearBounds() call have not been modified for an i-th vector component
Remove this block of code altogether.

2017-06-20 11:31 UTC, viciious commented on source/qcommon/cm_q3bsp.c
> +// Based on https://github.com/id-Software/Quake-III-Arena/blob/master/code/qcommon/cm_load.c
Please remove this comment

2017-06-20 11:31 UTC, viciious commented on source/qcommon/cm_q3bsp.c
> +	if( brush->numsides >= 6 ) {
This condition is always true. A collision brush can not contain less than 6 sides due to bevelling.

2017-06-20 11:31 UTC, viciious commented on source/qcommon/cm_local.h
> +// Its hard to imagine that there will be even larger maps in the future
This constant is not needed anymore.

2017-06-20 11:31 UTC, viciious commented on source/qcommon/cm_local.h
> +void    CMod_CalculateBrushBounds( cmodel_state_t *cms, cbrush_t *brush );
Please rename this function to CM_BoundBrush

2017-06-20 11:31 UTC, viciious commented on source/qcommon/cm_q3bsp.c
> +void CMod_CalculateBrushBounds( cmodel_state_t *cms, cbrush_t *brush ) {
CM_BoundBrush

2017-06-20 11:32 UTC, viciious requested changes

2017-06-20 11:32 UTC, viciious commented on source/qcommon/cm_q3bsp.c
> +			// If illegal bounds set by the ClearBounds() call have not been modified for an i-th vector component
Impossible condition branch.

2017-06-20 13:06 UTC, dnk777 commented
Thanks. I'll fix it 1-2 days later, I do not have mine build environment set up right now. Also I was struggling with uncrustify too here while trying to apply it on a newly rebased commit (I used a different version of it while starting to work on the CM). Can you tell your exact uncrustify version please?

2017-06-25 09:32 UTC, viciious commented
```
D:\Projects\qfusion\source>uncrustify.exe --version
uncrustify 0.64
```

2017-06-25 09:33 UTC, viciious requested changes

2017-06-25 09:33 UTC, viciious commented on source/qcommon/cm_q3bsp.c
> +	ClearBounds( brush->mins, brush->maxs );
This line is superfluous..

2017-06-25 21:50 UTC, viciious approved these changes

2017-06-25 21:51 UTC, merged