Fix builtin entity brushes bounds
Qfusion/qfusion pull request #403
Opened 2017-10-07 13:09 UTC by dnk777

While `cms->world_mins`, `cms->world_maxs` values seem to be valid to the time of these calls (as the CM initialization calls order points. Also I have printed these values to console for various maps), they are not really sufficient leading to weapons malfunction on regular DM maps. This glitch has not been noticed because I have been using only bomb maps for bots testing during recent months of development. You have suggested using «world bounds» instead of introducing huge numeric constants in discussion about the CM patch merging. In order to avoid introduction of ones I rely on `ClearBounds()` call for obtaining some huge components magnitude.

2017-10-07 17:31 UTC, viciious reviewed
This is an ugly piece of code

2017-10-07 20:11 UTC, viciious requested changes

2017-10-07 20:11 UTC, viciious commented on source/qcommon/cm_trace.c
> +#include <float.h>
All system-wide (<>) includes should precede the local ones ("")

2017-10-07 20:11 UTC, viciious commented on source/qcommon/cm_trace.c
> +	VectorSet( brush->mins, FLT_MIN, FLT_MIN, FLT_MIN );
FLT_MIN is defined as ~0 at least on some systems.

2017-10-07 20:11 UTC, viciious commented on source/qcommon/cm_trace.c
> +	VectorSet( brush->mins, FLT_MIN, FLT_MIN, FLT_MIN );
What you probably want here is some cmodel_state_t specific bounds, calculated as follows:
```
vec_t c1 = max( max( fabs( cms->world_mins[0] ), fabs( cms->world_mins[1] ) ), fabs( cms->world_mins[2] ) );
vec_t c2 = max( max( fabs( cms->world_maxs[0] ), fabs( cms->world_maxs[1] ) ), fabs( cms->world_maxs[2] ) );
vec_t c = max( c1, c2 );

VectorSet( cms->some_mins, -c, -c, -c );
VectorSet( cms->some_maxs, c, c, c );
```

Then you can get rid of this ugly two-liner function and revert back to VectorCopy or introduce a new function BoundsCopy in q_math instead

2017-10-08 09:49 UTC, dnk777 commented on source/qcommon/cm_trace.c
> +	VectorSet( brush->mins, FLT_MIN, FLT_MIN, FLT_MIN );
I am afraid of getting another surprise by using the proposed approach. Setting bounds to a huge value has been proven to be reliable (I have been using it during the CM patch development and it used to seem fine)

2017-10-08 09:51 UTC, dnk777 commented on source/qcommon/cm_trace.c
> +#include <float.h>
I avoid inclusion of this header now by using an integer constant (there will never be any maps exceeding the integer range bounds).

2017-10-08 10:03 UTC, viciious commented on source/qcommon/cm_trace.c
> +	VectorSet( brush->mins, FLT_MIN, FLT_MIN, FLT_MIN );
I won't merge the changeset in its current state. Please use the proposed approach which I outlined above.

2017-10-08 10:35 UTC, dnk777 commented on source/qcommon/cm_trace.c
> +	VectorSet( brush->mins, FLT_MIN, FLT_MIN, FLT_MIN );
I have tested it out of curiosity and it does not work (e.g. laser gun is unusable on small maps) https://github.com/dnk777/qfusion/tree/cm-wrong-brush-bounds-fix

2017-10-08 10:53 UTC, viciious commented
Btw, I'm yet to see explanation of why `cms->world_mins`, `cms->world_maxs` don't work.

2017-10-08 11:06 UTC, dnk777 commented
Looks like there is an additional offset/rotation applied to the trace absolute bounds, so from numeric POV it sometimes goes outside of the absolute world bounds. Thus I rather lean to using an apriori huge value for bounds components making translation/rotation negligible.

https://github.com/Qfusion/qfusion/blob/master/source/qcommon/cm_trace.c#L1030

2017-10-08 11:11 UTC, viciious commented
Possibly, yes, but they should still intersect...

2017-10-08 14:47 UTC, viciious requested changes

2017-10-08 14:47 UTC, viciious commented on source/qcommon/cm_q3bsp.c
> +
Superfluous empty line

2017-10-08 14:47 UTC, viciious commented on source/qcommon/cm_q3bsp.c
> +
Same thing here

2017-10-08 14:47 UTC, viciious commented on source/qcommon/cm_q3bsp.c
> +	VectorSet( cms->entity_brush_mins, -maxside, -maxside, -maxside );
Think we should add -1 here

2017-10-08 14:47 UTC, viciious commented on source/qcommon/cm_q3bsp.c
> +	VectorSet( cms->entity_brush_maxs, +maxside, +maxside, +maxside );
+1

2017-10-08 14:47 UTC, viciious commented on source/qcommon/cm_q3bsp.c
> +	float maxside;
float -> vec_t

2017-10-08 15:09 UTC, dnk777 commented on source/qcommon/cm_q3bsp.c
> +	VectorSet( cms->entity_brush_maxs, +maxside, +maxside, +maxside );
How about multiplying `maxside` by `2.0f` to guarantee if even initial trace bounds are shifted by an entire world dimension in `CM_TransformedBoxTrace` they're still within these maxside bounds?

2017-10-08 15:23 UTC, dnk777 commented on source/qcommon/cm_q3bsp.c
> +	VectorSet( cms->entity_brush_maxs, +maxside, +maxside, +maxside );
I am afraid that these `+/- 1` bounds still are not sufficient, but we are going to make the bug harder to detect.

2017-10-08 15:24 UTC, viciious commented on source/qcommon/cm_q3bsp.c
> +	VectorSet( cms->entity_brush_maxs, +maxside, +maxside, +maxside );
I can't see how trace bounds can fall outside cms->entity_brush bounds without overlapping them.. Please explain what exactly we're doing here in this PR..

2017-10-08 16:01 UTC, dnk777 commented on source/qcommon/cm_q3bsp.c
> +	VectorSet( cms->entity_brush_maxs, +maxside, +maxside, +maxside );
Looking at `CM_TransformedBoxTrace()` code: 

https://github.com/Qfusion/qfusion/blob/master/source/qcommon/cm_trace.c#L1030

Trace start/end points are translated if an origin is specified, then a rotation is applied (if specified). The rotation in some cases can move both these outside the specified brush bounds (neither translation nor rotation is applied while testing against the solid world).

The collision code is a bit confusing since it uses the same path for testing against the solid world and entities collision models. Tbh these code paths ideally should be separated and `CM_CollideBox()` for the entities path should not even check the bounds at all. However it leads either to huge code duplication or inefficiency (if an additional «skip bounds test» flag is introduced). So I have chosen initially to fill entities bounds by a huge value, so bounds tests acts as this flag test without introducing additional branching. Then you have suggested using world bounds while reviewing the former PR, but a bug discovery has spotted that was wrong.

2017-10-08 16:05 UTC, viciious commented on source/qcommon/cm_q3bsp.c
> +	VectorSet( cms->entity_brush_maxs, +maxside, +maxside, +maxside );
My question is, how those additional transform can potentially move it outside the world bounds without overlapping them.

2017-10-08 16:16 UTC, dnk777 commented on source/qcommon/cm_q3bsp.c
> +	VectorSet( cms->entity_brush_maxs, +maxside, +maxside, +maxside );
Non-solid-world collisions are perfomed not in world absolute coordinate system, but in a system relative to entity, and then results are transformed back to the world coordinate system.

https://github.com/Qfusion/qfusion/blob/master/source/qcommon/cm_trace.c#L1100

Thats why world bounds are not related to entities collision at all. Sorry for confusion, I have just noticed it too.

2017-10-15 11:41 UTC, viciious commented
Fixed in 20ba39e2e89ba4cfa69836ddf89524a3d85f2a1f

2017-10-15 11:41 UTC, closed without merging